name: release beta

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/CHANGELOG.md"

jobs:
  release:
    name: Release Beta
    runs-on: macos-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap
        run: |
          npx lerna bootstrap
          if [[ -n $(git status -s) ]]; then
            echo "Error: file tree is not clean"
            git status
            exit 1
          fi

      - name: Test
        run: npm run test

      - name: Build
        run: NODE_ENV=production npm run build

      - name: "Release"
        run: |
          npx lerna-from-npm
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --no-push --no-git-tag-version  --yes
          git commit -a -m 'DONT PUSH'
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npx lerna publish from-package --no-verify-access --pre-dist-tag beta --yes
          export RELEASE=$(cat lerna.json | jq -r '.version')
          git reset HEAD~ --hard
          git tag v$RELEASE
          git push origin v$RELEASE
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
