# based on: https://github.com/hirosystems/gh-actions-example/blob/main/.github/workflows/ci.yml
name: release

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"
    paths-ignore:
      - "**/CHANGELOG.md"
      - "**/package.json"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Set Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          git status

      - name: Bootstrap
        run: |
          npm run bootstrap
          git status

      - name: Test
        run: |
          npm run test
          git status

      - name: Build
        run: |
          NODE_ENV=production npm run build
          git status

      - name: "Release: Version"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          lerna version --conventional-commits --conventional-prerelease --preid beta --yes

      - name: "Release: Publish"
        run: lerna publish from-git --pre-dist-tag beta --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
